### ISSUE TITLE
动态切换，多账号

### ISSUE THREAD

**Issue by nogeek-cn** [Masterain98/Teto-CDN-controller#1]
例如：
一个域名，由 5 个阿里云的账号 + 5 个华为云的账号，混合部署，来刷免费的流量，不知道，你这个工程可以支持吗？

**Comment by Masterain98** [comment]
不可以，单一域名在同一个服务商下只能创建一个CDN服务。没做阿里云支持，支持了也只能1阿里云+1华为云

**Comment by nogeek-cn** [comment]
创建另外一个的时候，一开始的账号就会掉了？

**Comment by Masterain98** [comment]
服务商甚至不会允许你这么操作，这是技术限制

**Comment by nogeek-cn** [comment]
那我在想，是否可以

阿里云账号1
华为云账号1
腾讯云账号1

阿里云账号2
华为云账号2

的切换。

当阿里云账号1 切换为 华为账号1 的时候，删除 CDN，切换到 阿里云账号2 的时候绑定上去。

**Comment by Masterain98** [comment]
理论上可以，但考虑到各家免费流量的总量，省下的钱也追不上开发和维护成本。不如从本身系统结构上去优化，来减少CDN压力。
